name: Release

on:
  push:
    branches:
      - 'v*-signed'

jobs:

  release:
    name: Update release
    runs-on: ubuntu-24.04
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get version
        run: |
          BRANCH=${GITHUB_REF/refs\/heads\//}
          echo TAG=${BRANCH/-signed/} >> ${GITHUB_ENV}

      - name: Update release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${TAG} --clobber \
              wimboot src/wimboot.i386 src/wimboot.arm64

      - name: Clear prerelease flag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit ${TAG} --prerelease=false
